services:
  uph-clinica-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: uph-clinica-node
    restart: unless-stopped
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      PORT: "8000"
      UBICACION_ALMACEN: "sqlite:////app/base.db"
    volumes:
      - ./base.db:/app/base.db
