import type { FastifyInstance } from "fastify";
import { z } from "zod";
import type { SqliteDatabase } from "../db.js";
const schema=z.object({identidad:z.string(),no_colegiacion:z.string(),fecha_hora:z.string(),motivo:z.string()});
export async function registerAppointmentRoutes(app:FastifyInstance,db:SqliteDatabase){
 app.get("/citas/",async(req,rep)=>{const q=req.query as any;const rows=db.prepare("SELECT * FROM Citas LIMIT ? OFFSET ?").all(Math.min(Math.max(Number(q.limite??10),1),90),Math.max(Number(q.salto??0),0));if(!rows.length)return rep.code(404).send({detail:"No hay citas por mostrar"});return rows;});
 app.post("/citas/agendar_cita",async(req,rep)=>{const p=schema.safeParse(req.body);if(!p.success)return rep.code(422).send({detail:p.error.issues});const c=db.prepare("SELECT id FROM Clientes WHERE identidad=?").get(p.data.identidad) as any;if(!c)return rep.code(404).send({detail:"Paciente no encontrado"});const d=db.prepare("SELECT id FROM Doctores WHERE no_colegiacion=?").get(p.data.no_colegiacion) as any;if(!d)return rep.code(404).send({detail:"Doctor no encontrado"});if(Number.isNaN(Date.parse(p.data.fecha_hora)))return rep.code(400).send({detail:"Formato de fecha_hora invalido. formato ISO: YYYY-MM-DDTHH:MM:SS"});const r=db.prepare("INSERT INTO Citas (id_cliente,id_doctor,fecha_hora,motivo,estado) VALUES (?,?,?,?,?)").run(c.id,d.id,p.data.fecha_hora,p.data.motivo,"pendiente");return db.prepare("SELECT * FROM Citas WHERE id=?").get(r.lastInsertRowid);});
 app.patch("/citas/:cita_id/cancelar",async(req,rep)=>{const id=Number((req.params as any).cita_id);const c=db.prepare("SELECT * FROM Citas WHERE id=?").get(id) as any;if(!c)return rep.code(404).send({detail:`La cita con ID ${id} no existe`});if(c.estado!=="pendiente")return rep.code(400).send({detail:`Solo se pueden cancelar citas en estado 'pendiente'. Estado actual: ${c.estado}`});db.prepare("UPDATE Citas SET estado='cancelada' WHERE id=?").run(id);return {mensaje:"Cita cancelada exitosamente",cita_id:id,estado:"cancelada"};});
}
